### ISSUE TITLE
关于铭飞系统可维护性能的问题？

### ISSUE THREAD

**Issue by josephusmao** [ming-soft/MCMS#11]
现状描述：在类似的新闻模块，只能通过创建页面，更新页面的静态内容，将内容静态化后，然后替换对应的文件才能生效。数据既然已经入库，能否通过查询直接刷新出来，不用通过静态化。
痛点：只要有修改必须通过文件替换实现
需求点：数据入库，后台请求，直接展示出结果

**Comment by sky5454** [comment]
有API，详见Swagger生成的API文档，地址一般是http://localhost:8080/ms-mcms/swagger-ui.html
