### ISSUE TITLE
There is an Information disclosure  via /ms/index.do

### ISSUE THREAD

**Issue by tcsecchen** [ming-soft/MCMS#13]
Hello,my nickname is isecream, I found an Information disclosure in the /ms/index.do

First,access the page
![default](https://user-images.githubusercontent.com/25191604/50673480-f0663380-1018-11e9-9271-2d8655ca9f32.png)

the password of manager has been disclosured 
the md5 can be crack
![default](https://user-images.githubusercontent.com/25191604/50673512-2d322a80-1019-11e9-9ac8-6e2bb073123c.png)

**Comment by sky5454** [comment]
yes, actually the login api is also plaintext.
