### ISSUE TITLE
是否支持国际化配置？

### ISSUE THREAD

**Issue by yannuo0802** [ming-soft/MCMS#14]
是否支持国际化配置？

**Comment by zhaooptimus** [comment]
部署到Ubuntu上刚发现这个问题：不太支持。有些resources只有zh_CN版，并且全部使用不太local参数的getBundle来获取，导致某些资源会挂掉。看来只能 改locale  改代码 加resouces 三选一了。目前改locale最简单，剩余两种需要处理很多mingsoft的maven依赖包

**Comment by pljay** [comment]
大神怎么加入 国际化标签@zhaooptimus
