### ISSUE TITLE
[建议]关于MCMS标签的改进

### ISSUE THREAD

**Issue by sky5454** [ming-soft/MCMS#20]
1. 建议不处理注释里的标签，方便开发和测试
2. 建议抛出异常时，标明是哪个语句或者哪个模板的哪一行出现问题，而不是输出拼接之后的模板错误所在的行号
3. 标签不支持判断“栏目”是否有下一级，这个不方便导航栏的开发
4. `<#include "url">` 当url涉及相对路径时，include 时好时坏
5. 标签文档不详细，很难快速完全入手，建议在商店里增加一个开发演示的模板

**Comment by d1227731421** [comment]
5.1版本新增标签${field.childsize}	子分类数据可支持3
<#include "url">问题已处理
