### ISSUE TITLE
启动的时候报如下Caused by: java.lang.IllegalArgumentException: Result Maps collection already contains value for net.mingsoft.basic.dao.ICityDao.resultMap

### ISSUE THREAD

**Issue by xiaojun1209** [ming-soft/MCMS#26]
![E%TUKJQHI4ZJQJNRHW%Q B](https://user-images.githubusercontent.com/36891411/69488902-24ee1280-0eab-11ea-8422-4a53cc6ea178.png)
请问你们谁遇到过帮忙解决一下

**Comment by d1227731421** [comment]
请使用新版本，你那个问题基本是maven仓库不是最新的导致的
