### ISSUE TITLE
 BasicUtil类的getUrl方法中的request.getScheme()获取不到https的协议 

### ISSUE THREAD

**Issue by nirvanareborn** [ming-soft/MCMS#40]
工程用nginx作代理，添加了SSL证书，但是请求到后端后，BasicUtil类的getUrl方法中的request.getScheme()获取不到https的协议，导致一直是http，生成的页面中也都写死了http的请求，导致网站前后端异常。

**Comment by killfen** [comment]
添加证书后通过https访问后台重新生成一下。
