### ISSUE TITLE
安全问题-文章管理任意文件跨目录上传

### ISSUE THREAD

**Issue by Forgery1** [ming-soft/MCMS#42]
1、在文章管理，编辑一篇文章，可以上传文章缩略图
![image](https://user-images.githubusercontent.com/36876797/78654998-f885e080-78f7-11ea-9b0f-2251d7ce949f.png)
2、查看代码中对上传文件的限制，不允许上传exe和jsp文件
![image](https://user-images.githubusercontent.com/36876797/78655085-16ebdc00-78f8-11ea-88d0-1eb1f84cc1d3.png)
3、在文章缩略图哪里上传图片，拦截数据包，修改filename为**.jsp.    注意jsp后有个点，即可绕过对上传文件的限制（在windows系统上会自动去除后缀的最后一点.）
![image](https://user-images.githubusercontent.com/36876797/78655325-6f22de00-78f8-11ea-80a2-2360e1442d78.png)
4、由于代码中没有对../等特殊字符进行限制，我们通过修改uploadPath来实现任意目录穿越，这样我们可以吧jsp或exe文件上传到任意目录下。
![image](https://user-images.githubusercontent.com/36876797/78655541-bd37e180-78f8-11ea-91eb-b94d5a432271.png)
5、我们访问返回的url即可（要去点最后一个点）

**Comment by sky5454** [comment]
Please, all the security  problems should use  English. for that could stop somebody with evil to do that.

**Comment by d1227731421** [comment]
Use mcms 5.1 version, the official has solved the problem

**Comment by l0n3rs** [comment]
限制就是只能是目标机器为Windows:smile:
