### ISSUE TITLE
启动报错：java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getHttpServletMapping()Ljavax/servlet/http/HttpServletMapping;

### ISSUE THREAD

**Issue by KingBoyAndGirl** [ming-soft/MCMS#48]
![image](https://user-images.githubusercontent.com/48237066/103474085-3b1f0f80-4ddb-11eb-988f-8216477a9bae.png)
启动后访问：http://localhost:8080/ms_mcms/ms/login.do报错（上图所示）

**Comment by killfen** [comment]
请使用最新的5.2版本
