### ISSUE TITLE
数据库跟功能完全对应不上，新增角色报字段错误

### ISSUE THREAD

**Issue by afewnotes** [ming-soft/MCMS#49]
Error updating database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'create_by' in 'field list' ### The error may exist in net/mingsoft/basic/dao/IRoleDao.java (best guess) ### The error may involve net.mingsoft.basic.dao.IRoleDao.insert-Inline ### The error occurred while setting parameters ### SQL: INSERT INTO role ( role_name, manager_id, create_by, del, update_by ) VALUES ( ?, ?, ?, ?, ? ) ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'create_by' in 'field list' ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'create_by' in 'field list'

查了下，数据库里面就3个字段

**Comment by oneydaykoo** [comment]
ALTER TABLE `role`
ADD COLUMN `create_by` int(10) NULL COMMENT '创建人',
ADD COLUMN `create_date` datetime(0) NULL COMMENT '创建时间',
ADD COLUMN `update_by` int(10) NULL COMMENT '更新人',
ADD COLUMN `update_date` datetime(0) NULL COMMENT '更新时间',
ADD COLUMN `del` int(1) NULL COMMENT '删除标识';
执行以上SQL，应该是sql没同步更新。
