### ISSUE TITLE
About the label  Error 

### ISSUE THREAD

**Issue by Leevampire** [ming-soft/MCMS#52]
channel栏目标签使用ID排序后台报错。后台看到查询栏目表  拼接的id是cms_content.id，没有这个字段 select    id,   id as typeid,   category_title as typetitle,     CONCAT(category_path,'/index.html') as typelink,   category_keyword as typekeyword,   category_diy_url as typeurl,   category_flag as flag,   category_parent_ids as parentids,   category_descrip as typedescrip,  category_parent_ids as parentids,   category_type as type,  category_path as typepath,   leaf as typeleaf,   category_img as typelitpic ,   (select count(*) from cms_category c where c.category_id=id and c.del=0) as childsize   from cms_category     where    cms_category.del=0        ORDER BY    cms_content.id        asc

**Comment by oneydaykoo** [comment]
升级下sql
