### ISSUE TITLE
经常出现“站点not exists! ”错误

### ISSUE THREAD

**Issue by BeastTL** [ming-soft/MCMS#6]
正常操作，无规律突然跳出系统要求登录，登录以后提醒“站点not exists!”。

**Comment by sagittaria** [comment]
@BeastTL 试试把/WEB-INF/ms.install.bak 重命名去掉 .bak，我这样做之后可以正常登陆了

**Comment by BeastTL** [comment]
@sagittaria 是的，这样是可以解决问题，在官网的FAQ也有说明，但是真的是比较频繁的无来由的出现这样的问题，挺头疼的
