### ISSUE TITLE
没 jar包

### ISSUE THREAD

**Issue by im-Luxqi** [ming-soft/MCMS#8]
。。。

**Comment by im-Luxqi** [comment]
![image](https://user-images.githubusercontent.com/33117225/37588504-5bdfa79c-2b9d-11e8-860e-6f8c98739dbf.png)

**Comment by sky5454** [comment]
先让Maven下载一次依赖，这时可能会报某个jar没有在公共仓库 里，这时再把pom.xml里第一个仓库地址注释掉，再用Maven下载一次依赖即可。

原因：MCMS新的jar包大多放在 https://oss.sonatype.org/content/groups/public/
