### ISSUE TITLE
代码质量低下

### ISSUE THREAD

**Issue by aboutZZ** [ming-soft/MCMS#88]
花十分钟简单看了看你们的源码，想吐槽下

1. 还在使用老式风格`suffix pattern`，非要加个`.do`后缀，不明白意义何在。这玩意我记得是`struts2`那个时代的风格。Spring boot 早已弃用，建议去除。e.g. `/mcms/search.do`改为`/mcms/search`（PS. 你们程序员感觉还是十几年前老一套思想）
2. 在`Mybaitis plus`的`BaseMapper`和`IService`基础上又封装了一层，加入增删改查（`queryBySQL`、`saveEntity`、`deleteEntity`）等方法，但问题是这些操作`Mybaitis plus`都给你写好了，重复造轮子意义何在
3. 有些`Mapper`加了`@Component`注解，有些没加，麻烦统一下。要么你每个interface上用`@Mapper`注解，要么你用`@MapperSan`，我还没有见过用`@Component`的。说到`@MapperSan`，`MSApplication.java`里面`basePackages`竟然有`com.baomidou.**.mapper`这又是什么骚操作？感觉你们只要程序能运行起来不报错我别的啥都不管
4. 像`IBaseDao#saveEntity`、`BaseAction#getLocaleString`这些方法，标记为`deprecated`，但是代码里该用还是用，那你标记有啥用。
5. `BaseAction#getLocaleString`注释也写错了：`推荐使用 BasicUtil.getString`，应该是`BundleUtil.getLocaleString`吧？这样写注释，我开始怀疑程序会不会有其他bug了，连方法都能搞错。其他的`getUrl`、`getDomain`等不说了，一样的毛病

希望贵司不是为了KPI而开源，既然开源，咱就把代码写好，不要应付草草了事

**Comment by killfen** [comment]
谢谢犀利的评价
1、系统从2012年一直更新到现在，结构是传统的MVC模式，简单容易理解，不管是加不加.do都可以访问，是开发者个人意愿，我们强调规范，只要简单易懂我们觉得就可以，不是一味最求新的，这也让mcms的代码识别度高
2、Mybaitis plus 是2020年才开始升级，早期都是我们自己实现，提一个问题Mybatis plus能做复杂的关联且要进行多个数据库适配真方便？
3、这个的确有些插件存在这种情况，的确需要规范一下
4、因为Mcms老的版本用户都还在用。会在大版本更新的时候会彻底移除（就像jdk、spring也有过期方法但也不会说一升级版本就彻底拿掉，影响太大）
5、BasicUtil.getString 国底层单独抽离的方法，是从原来的控制层，迁移到BasicUtil工具类。

最后还是感谢您评论，

**Comment by aboutZZ** [comment]
- 作为MCMS框架本身，标记为`deprecated`的方法框架内部是不应该使用的，`deprecated`是提示给框架使用者看的。

- 第5点，`getLocaleString`方法是获取本地化文件字符，该方法的注释写的是推荐使用`BasicUtil.getString`，但是`BasicUtil.getString`方法是干嘛的？是获取客户端请求`param`的，两个方法实现的功能一样吗，能替换吗？你代码不报错是因为这两个方法都是传入两个String作为参数。
![呵呵](https://s2.loli.net/2022/03/07/Xu8kYpwlZFBMsGh.png)
