### ISSUE TITLE
存在token复用漏洞

### ISSUE THREAD

**Issue by CyberIKUN** [ming-soft/MCMS#91]
登录默认账号
![image](https://user-images.githubusercontent.com/83060696/161257005-03182bba-7d75-4ce9-9ea9-6b847ca5206f.png)
进入主页
![image](https://user-images.githubusercontent.com/83060696/161257210-3758c92c-0adf-4a18-928e-965a89514c1d.png)
F5刷新，拦截请求包
![image](https://user-images.githubusercontent.com/83060696/161257335-9122aaef-f5c5-4ae4-b501-0cbcfa51bc97.png)
复制Cookie，然后点击退出登录
![image](https://user-images.githubusercontent.com/83060696/161257415-f3136da0-75a1-42d6-a716-bc306ccfed24.png)
回到主页
![image](https://user-images.githubusercontent.com/83060696/161257551-977fd1d4-019a-41cd-8fab-df12e66f3202.png)
再次F5刷新，拦截请求包
![image](https://user-images.githubusercontent.com/83060696/161257607-36c9f423-1435-4ea9-993d-477d1f73fcaf.png)
加入刚刚复制的Cookie
![image](https://user-images.githubusercontent.com/83060696/161257726-35a0a933-95ae-4dec-b51e-3368e34dc692.png)
然后放包，成功进入主页
![image](https://user-images.githubusercontent.com/83060696/161257802-4a2c036b-20c2-464b-a874-64e35a39285c.png)
修复建议：
用户退出登录后，应销毁cookie

**Comment by killfen** [comment]
5.2.9 fix it
