### ISSUE TITLE
Token reuse vulnerability exists

### ISSUE THREAD

**Issue by CyberIKUN** [ming-soft/MCMS#92]
Login default account   username:msopen password:msopen
![image](https://user-images.githubusercontent.com/83060696/161270255-694af1e8-500c-4542-8376-aba5c0c79e7c.png)
Enter the home page
![image](https://user-images.githubusercontent.com/83060696/161270315-f1aaa050-e0f4-4425-b2f0-40add017990e.png)
F5 refresh and intercept request packets
![image](https://user-images.githubusercontent.com/83060696/161270386-446df2f3-20c7-4765-9313-0319edd33c32.png)
Copy the Cookie and click 退出 to log in
![image](https://user-images.githubusercontent.com/83060696/161270459-379e7aa8-ae94-424e-90f6-c732dbba2b41.png)
Back to the home page
![image](https://user-images.githubusercontent.com/83060696/161270513-2cffe8a8-5058-4a4d-af4a-438e98477c6c.png)
Press F5 again to refresh and intercept the request packet
![image](https://user-images.githubusercontent.com/83060696/161270543-22c81910-eb7c-4380-8680-ba68bb68d498.png)
Add the cookie you just copied
![image](https://user-images.githubusercontent.com/83060696/161270581-83442b4d-7707-4412-8a0c-33cf99fea228.png)
Then put the package and successfully enter the home page
![image](https://user-images.githubusercontent.com/83060696/161270620-d9646710-4ec7-4ecc-b350-5ccd9b265daa.png)
Repair suggestions:
After the user logs out, the cookie should be destroyed

**Comment by killfen** [comment]
5.2.9 fix it
