### ISSUE TITLE
Arbitrary user privilege promotion 

### ISSUE THREAD

**Issue by CyberIKUN** [ming-soft/MCMS#93]
Login with default account
![image](https://user-images.githubusercontent.com/83060696/161295151-f50f97fb-0571-4291-b861-6fd940ce8fad.png)
click on 权限管理
![image](https://user-images.githubusercontent.com/83060696/161295245-4e319c4c-b91b-47ac-a5ad-05f6f1eb367d.png)
As shown below，click on 角色管理
![image](https://user-images.githubusercontent.com/83060696/161295463-236a41c2-a99d-4313-9659-b02064f8157c.png)
click on 新增
![image](https://user-images.githubusercontent.com/83060696/161296877-9e9cea76-2f45-4146-8efa-d157093aa574.png)
Add permissions and username as shown
![image](https://user-images.githubusercontent.com/83060696/161297384-d7a6ff8c-27ad-4899-a294-84cc601f0504.png)
click on 保存
![image](https://user-images.githubusercontent.com/83060696/161297487-fe046d87-9696-46c7-a77e-c8766c3e3bc6.png)
click on 管理员管理
![image](https://user-images.githubusercontent.com/83060696/161297575-6b129f47-a0cf-42e8-b59c-ebb759096a93.png)
click on 新增
![image](https://user-images.githubusercontent.com/83060696/161297844-c6f9f15d-0852-4adf-8f04-774a6464d691.png)
click on 保存 . The added password is 123456
![image](https://user-images.githubusercontent.com/83060696/161298195-3979e031-a418-480b-be90-5109271430f0.png)
Back to 角色管理
![image](https://user-images.githubusercontent.com/83060696/161304525-754450c9-81c9-47e2-83f7-7c748851ab68.png)
click on 编辑
![image](https://user-images.githubusercontent.com/83060696/161308732-008ca9cd-428a-4bc9-a744-f2a7782daa94.png)
Check the content as shown in the figure, and then click the 保存  button to intercept the request package
![image](https://user-images.githubusercontent.com/83060696/161308819-108f6c38-13b3-45c8-a026-7914835930d5.png)
right-click in the blank space, pop up the menu bar, select Send to Repeater, and then click the drop button
![image](https://user-images.githubusercontent.com/83060696/161309149-28c49a9d-f62c-4b2c-ba40-990725eae1f2.png)
click on 退出
![image](https://user-images.githubusercontent.com/83060696/161298385-081aba5a-a103-4a2d-a14b-c877ba4fe4f2.png)
click on 确定
![image](https://user-images.githubusercontent.com/83060696/161298653-7765b5f5-b365-4df6-8765-ecf890b04260.png)
Log in with the low-privilege account password you just added
![image](https://user-images.githubusercontent.com/83060696/161298949-a3d0ba7a-1be6-40a9-9418-8c779de5bfc8.png)
click on 权限管理 ，and intercept the request packet and the returned response packet at the same time
![image](https://user-images.githubusercontent.com/83060696/161299025-fa4e8684-9e52-4cb7-928c-110e859edd3f.png)
Log the cookie from the first request packet
![image](https://user-images.githubusercontent.com/83060696/161305871-6b7f4a1e-6227-45d9-b685-e20781686a85.png)
click on 角色管理
![image](https://user-images.githubusercontent.com/83060696/161300184-c711aaf3-2ccb-46c9-baad-3fa782131dc7.png)
We can see that there are no edit and delete buttons in these two lines
![image](https://user-images.githubusercontent.com/83060696/161300225-08013c29-f55c-4192-b0c4-b4f28463346c.png)
Next back to the Repeater of burpsuite

Use the cookie of the low-privilege account normaluser to replace the cookie of the high-privilege account msopen
![image](https://user-images.githubusercontent.com/83060696/161309636-e2335583-7231-4b6c-9871-76647e04431d.png)

click on send
![image](https://user-images.githubusercontent.com/83060696/161309737-1658675b-2625-4d4c-b9b6-f582d8ec12d0.png)
We found that we used the cookie of the low-privilege account to construct the privilege-enhancing data package, and the returned result was successful, indicating that we could use the low-privilege account to modify and enhance our privileges，
also indicating that the program does not perform permission checking.

Then we F5 refresh the page
click on 权限管理
![image](https://user-images.githubusercontent.com/83060696/161310101-b621e88b-1d62-4f17-b15a-3e581ac47a17.png)
click on 角色管理，We found that we can now have edit and delete permissions
![image](https://user-images.githubusercontent.com/83060696/161310327-39493d06-f47b-4816-ac37-ea484dad398b.png)
click on 编辑
![image](https://user-images.githubusercontent.com/83060696/161310425-3d1db7fe-9e4d-4728-ae1b-f3088069fe1a.png)
![image](https://user-images.githubusercontent.com/83060696/161310445-e9b1989c-4ce8-4149-80b7-d44b818574ee.png)

Violate success

**Comment by killfen** [comment]
5.2.9 fix it
