### ISSUE TITLE
Mcms  v5.2.8文件上传漏洞

### ISSUE THREAD

**Issue by 1orangeSky** [ming-soft/MCMS#95]
1.代码分析
从铭飞官网https://gitee.com/mingSoft/MCMS把源码考下来之后
经过审计找到上传点，form.ftl这里有个文章缩略图上传点看他有没有做过滤然后根据action找到上传接口
<img width="415" alt="1" src="https://user-images.githubusercontent.com/106334576/170712617-eed47160-7a48-47b7-81e2-04c5e7837b39.png">

经过查找在FileAction.class这里只判断了../防止目录跳跃，继续往下看点击继承的那个类
<img width="416" alt="2" src="https://user-images.githubusercontent.com/106334576/170713789-41f4735e-5954-465e-9c79-d1c0d480c8fc.png">
BaseFileAction.class发现他这做了后缀判断接着看是在哪调用的过滤
<img width="415" alt="3" src="https://user-images.githubusercontent.com/106334576/170714186-91554a14-269d-4135-b5df-1bf5c80e8fef.png">
我们复制denied全局搜索，application.yml发现他是在配置文件里写了过滤，过滤了 exe,jsp,jspx,sh那说明除了这四个其他都可以上传
<img width="416" alt="4" src="https://user-images.githubusercontent.com/106334576/170716667-4949e5b5-c099-4688-a401-7ce55be9732f.png">
<img width="416" alt="5" src="https://user-images.githubusercontent.com/106334576/170717040-717e5010-395b-491d-887e-64d6c1fd510c.png">
接着看看他有没有可利用的接口来实现上传jsp，经过查找TemplateAction.class里有个专门解析zip的接口。那么结合上面的过滤 可以上传zip，可以通过zip包含jsp恶意文件上传上去  然后调用这个接口去解析zip并解析树jsp并访问。
<img width="415" alt="6" src="https://user-images.githubusercontent.com/106334576/170720725-ab638239-13da-447f-94fe-0b9dbd711b4e.png">

2.根据分析的代码操作
找到文章缩略图地址，点击上传zip
<img width="365" alt="7" src="https://user-images.githubusercontent.com/106334576/170720925-762d4302-3c03-4046-a65c-5d4a88d05887.png">
<img width="415" alt="8" src="https://user-images.githubusercontent.com/106334576/170723495-b00f2d51-0a27-4e9c-bd47-5300b8687d12.png">
上传上去之后右键复制图片路径，然后通过上面分析的调用解析zip的接口fileUrl=刚刚上传的zip回车提示执行成功
<img width="415" alt="9" src="https://user-images.githubusercontent.com/106334576/170723834-9584c5fb-1dda-4c05-959e-17d490acc949.png">
<img width="416" alt="10" src="https://user-images.githubusercontent.com/106334576/170724120-7dd8b2f6-601e-45d6-b8e0-3e81ad48aa7d.png">
<img width="416" alt="11" src="https://user-images.githubusercontent.com/106334576/170724354-027c7d16-0a65-43c1-a61e-23f186893c74.png">
之后查看上传目录的地方，发现成功解压了在通过路径访问aaaaa.jsp，然后利用哥斯拉去连接他发现执行成功
<img width="416" alt="12" src="https://user-images.githubusercontent.com/106334576/170724472-b4fb5ddd-8e85-4c89-b8d2-546ab4821201.png">
<img width="415" alt="13" src="https://user-images.githubusercontent.com/106334576/170724763-4deb02e6-ea90-44aa-b6ec-1d7502704436.png">
<img width="415" alt="14" src="https://user-images.githubusercontent.com/106334576/170725035-1f8ade4a-98df-4bd2-8165-91712a04bcfa.png">

.

**Comment by killfen** [comment]
5.2.9 fix it

**Comment by 1orangeSky** [comment]
需要tomcat启动



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月04日 15:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ming-soft/MCMS] Mcms  v5.2.8文件上传漏洞 (Issue #95) |

您是如何配置环境的，我用idea搭建环境后，存放上传文件的目录下不对jsp文件进行解析
