### ISSUE TITLE
Mingsoft MCMS v5.2.8 SQL注入【后台】

### ISSUE THREAD

**Issue by thunder-sec** [ming-soft/MCMS#97]
# 漏洞分析

漏洞路由位置/${ms.manager.path}/mdiy/page/verify，漏洞点在如下方法，if...else两个条件中的validated方法均存在问题。

<img width="1388" alt="image-20220717104840622" src="https://user-images.githubusercontent.com/76940213/179385662-6320f8e4-9a66-4a5d-a720-1e7bec901c13.png">

调用了父类的`validated`方法，validated方法中将传入的fieldName和fieldValue复制where对象中，并调用了`appBiz.queryBySQL`方法。

<img width="1479" alt="image-20220717104959321" src="https://user-images.githubusercontent.com/76940213/179385708-cfe81e18-5d49-4a5c-a8de-a2a3a1b097e1.png">

queryBySQL的实现方法如下调用了`getDao().queryBySQL(table, fields, wheres, null,null,  null, null,null);`

<img width="1516" alt="image-20220717102319042" src="https://user-images.githubusercontent.com/76940213/179385728-1ac61c92-8f8a-47d7-955a-2176ff6827e6.png">

<img width="1672" alt="image-20220717102446760" src="https://user-images.githubusercontent.com/76940213/179385735-98fa8c1c-dcda-415d-acba-82fe9baef143.png">

getDao().queryBySQL调用的具体SQL语句如下，其中key值对应的Map类型对象where，也就是前端传进来的fieldName

<img width="1495" alt="image-20220717102719639" src="https://user-images.githubusercontent.com/76940213/179385784-f1310147-4dc9-45db-b45a-65bdc532f1f4.png">

# 漏洞验证

构造如下请求包，如果数据库长度大于1，即成功睡眠3秒。

<img width="1792" alt="image-20220717104101033" src="https://user-images.githubusercontent.com/76940213/179385804-e8e95e83-1606-4600-99bc-607b94d732eb.png">

debug输出sql语句

<img width="1791" alt="image-20220717104329648" src="https://user-images.githubusercontent.com/76940213/179385817-3722476e-f15e-496e-9b82-b22407ceb3cc.png">

**Comment by killfen** [comment]
5.2.9 fix it
